/**
 * +===================================+
 * |  File auto-generated by SeamRPC.  |
 * |        --- DO NOT EDIT ---        |
 * +===================================+
 */

import { callApi, Result, RpcError } from "@seam-rpc/client";

/**
 * Creates a post and returns its ID.
 * @param title The title of the post.
 * @param content The conent of the post.
 * @returns ID of the newly created post.
 */
export function createPost(input: { authorId: string; title: string; content: string }): Promise<Result<string>> {
    return callApi("posts", "createPost", input);
}

/**
 * Gets the list of all posts.
 * @returns Array of posts.
 */
export function getPosts(): Promise<Result<{
    id: string;
    author: {
        id: string;
        name: string;
        age: number;
    };
    title: string;
    content: string;
}[]>> {
    return callApi("posts", "getPosts");
}