/* Auto-generated by SeamRPC - DO NOT EDIT */

import { callApi } from "@seam-rpc/client";

export function createPost(data: { authorId: string, title: string, content: string }): Promise<string> { return callApi("posts", "createPost", data); }

export function getPosts(data: {  }): Promise<void> { return callApi("posts", "getPosts", data); }