/* Auto-generated by SeamRPC - DO NOT EDIT */

import { callApi } from "@seam-rpc/client";

export function createPost(input: { authorId: string, title: string, content: string }): Promise<string> { return callApi("posts", "createPost", input); }

export function getPosts(): Promise<{
    id: string;
    author: {
        id: string;
        name: string;
        age: number;
    };
    title: string;
    content: string;
}[]> { return callApi("posts", "getPosts"); }