/* Auto-generated by SeamRPC - DO NOT EDIT */

import { callApi } from "@seam-rpc/client";

export function createUser(data: { name?: string | undefined, age: number }): Promise<{
    id: string;
    name: string;
    age: number;
}> { return callApi("users", "createUser", data); }

export function getUser(data: { id: string }): Promise<{
    id: string;
    name: string;
    age: number;
} | undefined> { return callApi("users", "getUser", data); }

export function getUsers(data: {  }): Promise<{
    id: string;
    name: string;
    age: number;
}[]> { return callApi("users", "getUsers", data); }

export function uploadFile(data: { file: File }): Promise<File> { return callApi("users", "uploadFile", data); }