/**
 * +===================================+
 * |  File auto-generated by SeamRPC.  |
 * |        --- DO NOT EDIT ---        |
 * +===================================+
 */

import { callApi } from "@seam-rpc/client";

/**
 * Creates a new user and returns it.
 * @param name The name of the user.
 * @param age The age of the user.
 * @returns The newly created user.
 */
export function createUser(input: { name: string; age: number }): Promise<{
    id: string;
    name: string;
    age: number;
}> {
    return callApi("users", "createUser", input);
}

export function getUser(input: { id: string }): Promise<{
    id: string;
    name: string;
    age: number;
} | undefined> {
    return callApi("users", "getUser", input);
}

export function getUsers(): Promise<{
    id: string;
    name: string;
    age: number;
}[]> {
    return callApi("users", "getUsers");
}

export function uploadFile(input: { file: File }): Promise<File> {
    return callApi("users", "uploadFile", input);
}