/**
 * +===================================+
 * |  File auto-generated by SeamRPC.  |
 * |        --- DO NOT EDIT ---        |
 * +===================================+
 */

import { callApi } from "@seam-rpc/client";

/**
 * Creates a new user and returns it.
 * @param name The name of the user.
 * @param age The age of the user.
 * @returns The newly created user.
 */
export function createUser(input: { name: string; age: number }): Promise<{ ok: false; error: string; data?: undefined; } | { ok: true; data: { id: string; name: string; age: number; }; error?: undefined; }> {
    return callApi("users", "createUser", input);
}